# training
conf_id: VOC_plain_051622
algorithm: Plain
num_iters: 30000
# num_epochs: 2
log_interval: 10
parallel: 0

# data
dataset_root: /home/ubuntu/efs/VOC/VOCdevkit/VOC2012
dataset_name: VOC
num_classes: 21
batch_size: 16
# batch_size: 2
num_workers: 2

# model
model_name: DeepLabV3_ResNet50
num_layers: 50
weights_init: ImageNet

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0004
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0004
## lr_scheduler
step_size: 10000
gamma: 0.1
